from lib import login,update_proxy,get_host_by_hostid,get_proxys
from pprint import pprint

hosts_jgs = [
    {'host': 'SULJVE-AQI-NSM5-ap-Sul_Internet_Araquari_C', 'hostid': '19122'},
    {'host': 'TFI-GMM-RKT-ap-caixadagua-03', 'hostid': '20320'},
    {'host': 'RVIP-BVH-RKT-ap-ricbarra-01', 'hostid': '20066'},
    {'host': 'SULJVE-JVE-MT5-ap-torreft-01', 'hostid': '19899'},
    {'host': 'SULJVE-ITH-RKT-ap-TORRE_RADIO_04', 'hostid': '20233'},
    {'host': 'RVIP-BVH-RKT-ap-saocristovao-04', 'hostid': '19984'},
    {'host': 'RVIP-PEN-RKT-ap-pedradailha-04', 'hostid': '22323'},
    {'host': 'SULJVE-ITH-SXT-ap-brasmar', 'hostid': '19868'},
    {'host': 'TFI-JGS-RB921-boavista-luisleigue', 'hostid': '19422'},
    {'host': 'SULJVE-GRV-NS5-SUL_BOMFUTURO_B', 'hostid': '21186'},
    {'host': 'TFI-JGS-RKT-ap-lindomar-04', 'hostid': '15235'},
    {'host': 'RVIP-SCH-RKT-ap-guilhermedaren-03', 'hostid': '12098'},
    {'host': 'RVIP-BVH-RKT-ap-saocristovao-02', 'hostid': '19982'},
    {'host': 'TFI-GMM-RKT-ap-carolina-01', 'hostid': '15211'},
    {'host': 'TFI-JGS-RKT-ap-esterminel-03', 'hostid': '15251'},
    {'host': 'RVIP-SCH-RKT-ap-guilhermedaren-01', 'hostid': '12096'},
    {'host': 'TFI-GMM-RKT-ap-amizade-05', 'hostid': '19439'},
    {'host': 'RVIP-SCH-RKT-ap-guilhermedaren-02', 'hostid': '12097'},
    {'host': 'TFI-JGS-RKT-ap-esterminel-01', 'hostid': '15252'},
    {'host': 'TFI-JGS-RKT-ap-elcidio-04', 'hostid': '20738'},
    {'host': 'SULJVE-ITH-RKT-ap-SAMAMBAIA_BB', 'hostid': '20239'},
    {'host': 'RVIP-BVH-RKT-ap-acorianos-01', 'hostid': '19876'},
    {'host': 'RVIP-BVH-RKT-ap-costadoouro-05', 'hostid': '20058'},
    {'host': 'RVIP-BVH-RKT-ap-acorianos-02', 'hostid': '19877'},
    {'host': 'RVIP-BVH-Router-Acorianos', 'hostid': '19865'},
    {'host': 'RVIP-BVH-RKT-ap-acorianos-03', 'hostid': '19878'},
    {'host': 'RVIP-BVH-Router Costa do Ouro', 'hostid': '19860'},
    {'host': 'ED-JGS-FRANCISCODALPRA-BLOCO1', 'hostid': '26293'},
    {'host': 'TFI-JGS-RKT-ap-TPA MQ 1', 'hostid': '14970'},
    {'host': 'TFI-JGS-Router Macaquinho', 'hostid': '14980'},
    {'host': 'TFI-JGS-RKT-ap-rotcha-02', 'hostid': '15033'},
    {'host': 'TFI-JGS-RKT-ap-TPA MQ 4', 'hostid': '14973'},
    {'host': 'TFI-JGS-RKT-ap-TPA MQ 2', 'hostid': '14971'},
    {'host': 'TFI-JGS-MKT-sw-riodaluz3', 'hostid': '15042'},
    {'host': 'TFI-JGS-MKT-sw-pedaserra2', 'hostid': '15084'},
    {'host': 'TFI-JGS-RKT-ap-UNI-JGS-MQ-4B', 'hostid': '14978'},
    {'host': 'TFI-JGS-RKT-ap-rotcha-01', 'hostid': '15031'},
    {'host': 'TFI-JGS-RKT-ap-TPA MQ 5', 'hostid': '14974'},
    {'host': 'TFI-JGS-RKT-ap-TPA RC II 3', 'hostid': '15034'},
    {'host': 'TFI-JGS-RKT-ap-TPA RLIII', 'hostid': '15038'},
    {'host': 'TFI-JGS-RKT-ap-TPA PS 2', 'hostid': '15083'},
    {'host': 'TFI-JGS-RKT-ap-UNI-JGS-BVC-1D', 'hostid': '15392'},
    {'host': 'TFI-JGS-MKT-sw-tifaschubert-2', 'hostid': '14905'},
    {'host': 'TFI-JGS-MKT-sw-tifaschubert-1', 'hostid': '14906'},
    {'host': 'TFI-JGS-MKT-sw-casaamarela', 'hostid': '15331'},
    {'host': 'SULJVE-JVE-LB-ceasa-rudnick', 'hostid': '25395'},
    {'host': 'TFI-GMM-MKT-sw-bananalneja', 'hostid': '15205'},
    {'host': 'TFI-GMM-RKT-ap-brisadovale-01', 'hostid': '18923'},
    {'host': 'TFI-GMM-RKT-ap-hsk-01', 'hostid': '15247'},
    {'host': 'TFI-GMM-Router HSK', 'hostid': '15259'},
    {'host': 'TFI-GMM-MKT-sw-brisadovale', 'hostid': '18922'},
    {'host': 'SULJVE-ITH-PB-paraty-serrinha', 'hostid': '27781'},
    {'host': 'SULJVE-ITH-PB-serrinha-paraty', 'hostid': '27780'},
    {'host': 'TFI-GMM-RKT-ap-hsk-02', 'hostid': '15261'},
    {'host': 'RVIP-BVH-RKT-ap-ricbarra-02', 'hostid': '20067'},
    {'host': 'RVIP-BVH-RKT-ap-ricbarra-04', 'hostid': '20069'},
    {'host': 'SULJVE-ITH-LB-samambaial-saneamento', 'hostid': '25971'},
    {'host': 'TFI-JGS-Router Jaragua 84 Alto', 'hostid': '15141'},
    {'host': 'RVIP-SCH-RKT-ap-fritzke-02', 'hostid': '11957'},
    {'host': 'RVIP-SCH-RKT-ap-krogel-01', 'hostid': '12028'},
    {'host': 'SULJVE-JVE-Router Cond Kaiser', 'hostid': '18977'},
    {'host': 'TFI-JGS-Router Larissa', 'hostid': '15112'},
    {'host': 'TFI-GMM-RKT-ap-dolarico-03', 'hostid': '22994'},
    {'host': 'TFI-GMM-MKT-sw-dolarico', 'hostid': '22938'},
    {'host': 'TFI-GMM-Router Centro', 'hostid': '15218'},
    {'host': 'TFI-GMM-RKT-ap-dolarico-01', 'hostid': '22940'},
    {'host': 'TFI-GMM-RKT-ap-centro-01', 'hostid': '15219'},
    {'host': 'TFI-GMM-NB-centro-monet', 'hostid': '15221'},
    {'host': 'TFI-GMM-NB-centro-saogabriel', 'hostid': '15222'},
    {'host': 'CUSTOMER-IAI-SSP-FELIPE-SCHMIDT-CENTRO', 'hostid': '28312'},
    {'host': 'SULJVE-JVE-RB912-viena-rudnick', 'hostid': '25577'},
    {'host': 'SULJVE-JVE-RB912-rudnick-viena', 'hostid': '25578'},
    {'host': 'SULJVE-JVE-Router-Amazonas-1', 'hostid': '19092'},
    {'host': 'ED-JGS-ESTACOES-BLPRIMAVERA', 'hostid': '16135'},
    {'host': 'ED-JGS-ESTACOES-BLOUTONO', 'hostid': '16136'},
    {'host': 'ED-JGS-ERIKAMODROCK-BL3', 'hostid': '15469'},
    {'host': 'ED-JGS-ERIKAMODROCK-BL4', 'hostid': '15470'},
    {'host': 'ED-JGS-ERIKAMODROCK-BL7', 'hostid': '15473'},
    {'host': 'ED-JGS-ERIKAMODROCK-BL8', 'hostid': '15474'},
    {'host': 'ED-JGS-BRASILIABELTRAMINI-BL4', 'hostid': '15491'},
    {'host': 'ED-JGS-ONIX', 'hostid': '21585'},
    {'host': 'ED-JGS-GARCIA', 'hostid': '21586'},
    {'host': 'ED-JGS-SILVANACLEIDE-BLOCO4', 'hostid': '21955'},
    {'host': 'ED-JGS-ELZA-BLC', 'hostid': '21588'},
    {'host': 'ED-JGS-BRUNAMARIANA', 'hostid': '21958'},
    {'host': 'ED-JGS-NOVOSCAMINHOS-BL1', 'hostid': '21591'},
    {'host': 'ED-JGS-SILVANACLEIDE-BLOCO1', 'hostid': '21957'},
    {'host': 'ED-JGS-MARANELLO', 'hostid': '21960'},
    {'host': 'ED-JGS-CAETE', 'hostid': '21959'},
    {'host': 'ED-JGS-RECANTO2', 'hostid': '21815'},
    {'host': 'ED-JGS-WALDEMIROBARTEL', 'hostid': '21834'},
    {'host': 'ED-JGS-LILIANEMMENDOERFER-BL19', 'hostid': '21640'},
    {'host': 'ED-JGS-HAUSGARTEN-BL12C-PRINCIPA', 'hostid': '21804'},
    {'host': 'ED-JGS-JARDIMAMERICA-BL4', 'hostid': '21828'},
    {'host': 'ED-JGS-GALAXY', 'hostid': '21826'},
    {'host': 'ED-JGS-GENESIS', 'hostid': '21830'},
    {'host': 'ED-JGS-MILAO', 'hostid': '21793'},
    {'host': 'ED-JGS-JARDIMEUROPA-BLPORTUGAL', 'hostid': '21770'},
    {'host': 'ED-JGS-JARDIMEUROPA-BLESPANHA', 'hostid': '21771'},
    {'host': 'ED-JGS-JARDIMEUROPA-BLGRECIA', 'hostid': '21782'},
    {'host': 'ED-JGS-HAUSGARTEN-BL14-PRINCIPAL', 'hostid': '21785'},
    {'host': 'ED-JGS-ESTERMINEL-BL11', 'hostid': '21619'},
    {'host': 'ED-JGS-ESTERMINEL-BL12', 'hostid': '21620'},
    {'host': 'ED-JGS-CATENA', 'hostid': '21590'},
    {'host': 'ED-JGS-FIDELIS.STINGHEN', 'hostid': '21943'},
    {'host': 'ED-JGS-DUBLIN', 'hostid': '21849'},
    {'host': 'ED-JGS-BUONGIORNO-BLB', 'hostid': '21895'},
    {'host': 'ED-JGS-EMAVIGUI', 'hostid': '21918'},
    {'host': 'TFI-JGS-MKT-sw-malharia', 'hostid': '20204'},
    {'host': 'TFI-JGS-RKT-ap-malharia-01', 'hostid': '20205'},
    {'host': 'TFI-JGS-RKT-ap-esterminel-04', 'hostid': '18979'},
    {'host': 'SULJVE-JVE-MT5-ptp-luxemburgo-miudau', 'hostid': '18729'},
    {'host': 'SULJVE-JVE-MT5-mildau-luxemburgo', 'hostid': '18730'},
    {'host': 'SULJVE-JVE-NSM5-ap-ARCD_C', 'hostid': '18899'},
    {'host': 'SULJVE-JVE-MKT-ap-Sul_Nova_Brasilia_A', 'hostid': '18956'},
    {'host': 'SULJVE-JVE-PB-ap-AP_TORRE_MB', 'hostid': '18957'},
    {'host': 'SULJVE-JVE-METAL5-ptp-eddeville-torreft', 'hostid': '19087'},
    {'host': 'SULJVE-JVE-MKT-sw-profipo', 'hostid': '19511'},
    {'host': 'SULJVE-JVE-NS5-ap-SUL_PROFIPO_A', 'hostid': '19512'},
    {'host': 'RVIP-BVH-PB-costadoouro-acorianos', 'hostid': '19872'},
    {'host': 'RVIP-BVH-PB-acorianos-costadoouro', 'hostid': '19875'},
    {'host': 'SULJVE-ITH-MKT-serrinha-perdidos_bameirindos', 'hostid': '19869'},
    {'host': 'SULJVE-GRV-MKT-perdidos-itapoa', 'hostid': '19870'},
    {'host': 'SULJVE-ITH-Router-Pousada', 'hostid': '20140'},
    {'host': 'SULJVE-ITH-PB-pousada-serrinha', 'hostid': '20161'},
    {'host': 'SULJVE-ITH-RKT-ap-Sul_Internet_Pousada_A', 'hostid': '20162'},
    {'host': 'SULJVE-ITH-NSM5-ap-Sul_Internet_Pousada_B', 'hostid': '20163'},
    {'host': 'SULJVE-ITH-MKT-sw-samambaial', 'hostid': '20244'},
    {'host': 'SULJVE-ITH-RKT-ap-SUL_POP_SAMAMBAIL_B', 'hostid': '20245'},
    {'host': 'SULJVE-ITH-RKT-ap-SUL_POP_SAMAMBAIL_A', 'hostid': '20246'},
    {'host': 'SULJVE-JVE-NETMETAL-loft-transamerica', 'hostid': '21174'},
    {'host': 'SULJVE-GRV-PB-ap-LStractor', 'hostid': '23088'},
    {'host': 'RVIP-SCH-RKT-ap-fritzke-01', 'hostid': '11955'},
    {'host': 'RVIP-SCH-RKT-ap-guilhermedaren-05', 'hostid': '12099'},
    {'host': 'RVIP-SCH-RKT-ap-aquarela-01', 'hostid': '16138'},
    {'host': 'RVIP-BVH-RKT-ap-popitajuba-06', 'hostid': '20408'},
    {'host': 'RVIP-SCH-RKT-ap-schneider-saopedro', 'hostid': '11993'},
    {'host': 'RVIP-SCH-RKT-ap-jpirene-01', 'hostid': '11986'},
    {'host': 'RVIP-SCH-Router R. Guilherme Daren', 'hostid': '12093'},
    {'host': 'RVIP-BVH-RKT-ap-lynus-03', 'hostid': '20558'},
    {'host': 'RVIP-PEN-RKT-ap-nautilus-01', 'hostid': '21269'},
    {'host': 'RVIP-SCH-Router Schneider', 'hostid': '11985'},
    {'host': 'RVIP-PEN-Router-Pedra_da_ilha', 'hostid': '22318'},
    {'host': 'RVIP-BVH-RKT-ap-popitajuba-05', 'hostid': '20407'},
    {'host': 'RVIP-BVH-RKT-ap-costadoouro-04', 'hostid': '19977'},
    {'host': 'RVIP-SCH-Router SCH Marcenaria', 'hostid': '12051'},
    {'host': 'RVIP-SCH-Router SCH Fritzke', 'hostid': '11950'},
    {'host': 'SULJVE-JVE-MKT-sw-solarcomerciarios', 'hostid': '19586'},
    {'host': 'SULJVE-JVE-NSM5-ap-Big_Band_Solar_5.8_D', 'hostid': '19590'},
    {'host': 'SULJVE-JVE-Router Morro Do Meio CEI', 'hostid': '18941'},
    {'host': 'SULJVE-JVE-Router Nova Brasilia', 'hostid': '18955'},
    {'host': 'SULJVE-JVE-Router Morro do Meio Colegio', 'hostid': '18948'},
    {'host': 'SULJVE-JVE-NSM5-ap-morrodomeiocei_A', 'hostid': '18942'},
    {'host': 'TFI-GMM-RKT-ap-bananal-03', 'hostid': '15190'},
    {'host': 'TFI-GMM-RKT-ap-couro-02', 'hostid': '15228'},
    {'host': 'TFI-GMM-RKT-ap-couro-01', 'hostid': '15229'},
    {'host': 'SULJVE-JVE-RKT-ap-kaiser_C', 'hostid': '18864'},
    {'host': 'SULJVE-JVE-RKT-ap-kaiser_B', 'hostid': '18863'},
    {'host': 'SULJVE-JVE-RKT-ap-kaiser_D', 'hostid': '18865'},
    {'host': 'SULJVE-JVE-RKT-ap-kaiser_A', 'hostid': '18862'},
    {'host': 'SULJVE-JVE-MKT-sw-golfclub', 'hostid': '19945'},
    {'host': 'SULJVE-JVE-RKT-ap-mildau_1', 'hostid': '18731'},
    {'host': 'SULJVE-ITH-RKT-ap-SAMAMBAIAL_D', 'hostid': '20253'},
    {'host': 'SULJVE-GRV-RKT-ap-Big_Band_Garuva_B', 'hostid': '19886'},
    {'host': 'SULJVE-ITH-Router-Radio-Itapoa', 'hostid': '20138'},
    {'host': 'SULJVE-GRV-RKT-ap-Big_Band_Garuva_C', 'hostid': '19891'},
    {'host': 'SULJVE-ITH-NSM5-ap-SUL_XAVANTES_D', 'hostid': '20266'},
    {'host': 'SULJVE-ITH-Router-Varela', 'hostid': '20141'},
    {'host': 'SULJVE-ITH-RB912-ap-SUL_PARATY_360', 'hostid': '20185'},
    {'host': 'SULJVE-GRV-Router Torre Garuva', 'hostid': '19884'},
    {'host': 'SULJVE-GRV-RKT-ap-Big_Band_Garuva_F', 'hostid': '19895'},
    {'host': 'SULJVE-ITH-RKT-ap-SAMAMBAIAL-P', 'hostid': '20242'},
    {'host': 'SULJVE-ITH-NSM5-ap-SAMAMBAIAL_EFORCES', 'hostid': '20243'},
    {'host': 'SULJVE-ITH-RKT-ap-SAMAMBAIAL-O', 'hostid': '20240'},
    {'host': 'SULJVE-ITH-RKT-ap-SAMAMBAIAL_AAA', 'hostid': '20254'},
    {'host': 'SULJVE-GRV-RKT-ap-Big_Band_Garuva_D', 'hostid': '19892'},
    {'host': 'SULJVE-ITH-RKT-ap-SAMAMBAIAL_BBB', 'hostid': '20249'},
    {'host': 'SULJVE-GRV-RKT-ap-Big_Band_Garuva_A', 'hostid': '19885'},
    {'host': 'SULJVE-GRV-RKT-ap-latina', 'hostid': '19889'},
    {'host': 'SULJVE-ITH-RKT-ap-SAMAMBAIA_AA', 'hostid': '20238'},
    {'host': 'SULJVE-ITH-MKT-sw-xavantes', 'hostid': '20262'},
    {'host': 'SULJVE-ITH-RKT-ap-SAMAMBAIAL-N', 'hostid': '20241'}
]

def main():
    auth = login()

    proxy = get_proxys(auth)[2]['id']

    for host in hosts_jgs:
        print('ANTES:')
        pprint(get_host_by_hostid(auth, host['hostid']))
        print()

        update_proxy(auth,host['hostid'], proxy)

        print('DEPOIS:')
        pprint(get_host_by_hostid(auth, host['hostid']))
        print()


if __name__ == '__main__':
    main()